# Book Easy Project

This project is a full-stack application consisting of a **mobile app** built with **Flutter** and a **backend API** built with **FastAPI**.

## Project Structure

The project is divided into two main directories:

- **backend/**: Contains the FastAPI backend for handling requests.
- **app/**: Contains the Flutter mobile app that interacts with the backend.

```
BookEasy/
│
├── backend/              # FastAPI backend
│   ├── app/
│   │   ├── __init__.py
│   │   ├── main.py       # Entry point for FastAPI application
│   │   ├── models.py     # Database models or Pydantic schemas
│   │   ├── routes.py     # API endpoints
│   │   └── utils.py      # Helper functions and utilities
│   ├── requirements.txt  # Project dependencies
│   └── README.md         # Backend README
│
├── app/                  # Flutter mobile app
│   ├── lib/
│   │   ├── main.dart     # Entry point for Flutter application
│   │   ├── screens/      # Screens for the mobile app
│   │   └── widgets/      # Reusable widgets
│   ├── pubspec.yaml      # Flutter dependencies and configuration
│   └── README.md         # Mobile app README
│
├── .gitignore            # Git ignore file to exclude virtualenv, build files, etc.
├── LICENSE               # Project license (e.g., MIT)
└── README.md             # This file (for the entire project)
```

## Requirements

### Backend

- Python 3.7+
- FastAPI
- Uvicorn

### Mobile App

- Flutter 2.x+
- Dart SDK

## Installation

### 1. Clone the repository

```bash
git clone <repository-url>
cd BookEasy
```

### 2. Backend Setup (FastAPI)

#### a. Navigate to the **backend/** directory:

```bash
cd backend
```

#### b. Create and activate a virtual environment:

**On Windows**:

```bash
python -m venv venv
.\venv\Scripts\activate
```

**On macOS/Linux**:

```bash
python3 -m venv venv
source venv/bin/activate
```

#### c. Install backend dependencies:

```bash
pip install -r requirements.txt
```

#### d. Run the FastAPI application:

```bash
uvicorn app.main:app --reload
```

The backend API will be available at:

```
http://127.0.0.1:8000
```

You can also view the API documentation at:

```
http://127.0.0.1:8000/docs
```

### 3. Mobile App Setup (Flutter)

#### a. Navigate to the **app/** directory:

```bash
cd app
```

#### b. Install Flutter dependencies:

```bash
flutter pub get
```

#### c. Run the Flutter application:

```bash
flutter run
```

This will launch the mobile app in your default simulator/emulator or connected device.

### 4. Connect Mobile App to Backend

Make sure your mobile app is pointing to the correct backend URL in your **Flutter** code (e.g., `http://127.0.0.1:8000` or the IP address of your backend server if running on a separate machine).

### 5. Documentation

Once the backend is running, you can view the interactive API documentation generated by FastAPI at:

```
http://127.0.0.1:8000/docs
```

Alternatively, you can view the ReDoc-generated documentation at:

```
http://127.0.0.1:8000/redoc
```

## Project Features

- **Backend**:
  - User authentication and authorization
  - CRUD operations for the app's resources (e.g., bookings, users)
  - RESTful API design using FastAPI
  
- **Mobile App**:
  - User-friendly interface built with Flutter
  - Interacts with the backend to manage bookings
  - Handles real-time data fetching and display

## License

This project is open-source and available under the [MIT License](LICENSE).